from django.shortcuts import render, redirect
from django.urls import reverse
from . import models

# Create your views here.
def list(request):
  all_cars = models.Car.objects.all()
  context = { "all_cars": all_cars }

  return render(request, 'cars/list.html', context = context)

def add(request):
  if request.POST:
    brand = request.POST["brand"]

    # interestingly even if this is not type casted to int,
    # and a string is passed for year,
    # it will still create the instance and it will be type int
    year = int(request.POST["year"])
    models.Car.objects.create(brand = brand, year = year)

    # redirect me to the url
    # url is generated by finding the reverse of "cars:list"
    # "cars:list" means, go to the car app, and find the url named "list"
  else:
    return redirect(reverse("cars:list"))

  return render(request, 'cars/add.html')

def delete(request):
  if request.POST:
    pk = request.POST["pk"]

    try:
      models.Car.objects.get(pk = pk).delete()
      return redirect(reverse("cars:list"))

    except:
      return redirect(reverse("cars:list"))

  else:
    return render(request, 'cars/delete.html')

